### PR TITLE
Update to version 7.1.3

### PR DESCRIPTION
**Pull request by dtchanpura**
The description uses `ul`/`li` tags instead of `p` for now.

### CODE REVIEW

**Comment by dtchanpura** [comment]
Continuing the discussion from #59, I do have another option we can just use which is URL in `<release />` I was looking at description and thought it won't work, but to simplify we can just add the GitHub release link of dbeaver/dbeaver

```xml
        <release version="7.1.3" date="2020-07-19" url="https://github.com/dbeaver/dbeaver/releases/tag/7.1.3" />
```

Reference: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases

**Comment by dac73** [comment]
I was thinking about that too, but this way would be prettier :/
Can you try to add `- ` in front of subelements? If this would work, I can automate it like that.

Example:
```
<li>Exasol: (thaks to @Sargul)</li>
<li>-  Database error type discovery was added (proper handle of "connection lost" errors)</li>
<li>-  Metadata read performance was improved</li>
```

**Comment by dac73** [comment]
Nah forget it, it will be ugly, let's just add url....

**Comment by dtchanpura** [comment]
I pushed it already. Let me push it with URL

**Comment by dtchanpura** [comment]
@dac73 Is there a way to see this changes locally?

**Comment by dac73** [comment]
I don't know of it, but I remember I already tried dashes in `<li>` :)
The only thing you can locally try is if validation will pass with `org.freedesktop.appstream-glib validate io.dbeaver.DBeaverCommunity.appdata.xml`

**Comment by dtchanpura** [comment]
Oh okay. Let me know if this looks good. The changes include just the URL.

**Pull request merged**
