### PR TITLE
Updated to 6.0.5 release

### PR DESCRIPTION
**Pull request by samiconductor**

### CODE REVIEW

**Comment by samiconductor** [comment]
Not sure what the issue is. That [license](https://dbeaver.io/files/dbeaver_license.txt) URL is valid. And the [6.0.2 archive](https://github.com/dbeaver/dbeaver/releases/download/6.0.2/dbeaver-ce-6.0.2-linux.gtk.x86_64.tar.gz) is also a valid URL.

**Comment by krashekspres** [comment]
bot, build

**Comment by krashekspres** [comment]
Well, looks like we have some old problems which went undetected until now, can you please fix them in your PR since you started it :)
All changes are in `io.dbeaver.DBeaverCommunity.appdata.xml`
1. `• tag-invalid           : <metadata_license> is not valid [Apache-2.0]`
    - change it to `<metadata_license>CC0-1.0</metadata_license>`
1. `• tag-invalid           : <project_license> is not valid [LicenseRef=https://dbeaver.io/files dbeaver_license.txt]SPDX ID 'LicenseRef=https://dbeaver.io/files/dbeaver_license.txt' unknown`
    - change it to `<project_license>Apache-2.0</project_license>`
1. `• style-invalid         : <caption> is too short [ERD];shortest allowed is 5 chars` 
    - rename to `Entity Relationship Diagram`

1. `• file-invalid          : <screenshot> failed to load [https://github.com/dbeaver/dbeaver/releases/download/6.0.2/dbeaver-ce-6.0.2-linux.gtk.x86_64.tar.gz]`
    - change to `https://dbeaver.io/product/dbeaver-ss-classic.png`

:+1:

**Comment by samiconductor** [comment]
Sure @krashekspres. For that invalid screenshot (4th issue), that release URL was hanging out next to the caption tag. I just removed it.

**Comment by krashekspres** [comment]
@samiconductor awesome job, thank you.

**Pull request merged**
